version: '3.8'

services:
  summeet-backend:
    build: .
    container_name: summeet-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

# Example nginx configuration for your external proxy:
# 
# server {
#     listen 80;
#     server_name your-domain.com;
#     
#     # Increase file upload size limit
#     client_max_body_size 200M;
#     client_body_timeout 300s;
#     client_header_timeout 300s;
#     
#     location / {
#         proxy_pass http://localhost:8000;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_request_buffering off;
#         proxy_read_timeout 900s;
#         proxy_connect_timeout 300s;
#         proxy_send_timeout 900s;
#         proxy_buffering off;
#         proxy_max_temp_file_size 0;
#     }
# }